[package]
name = "winit-platform"
version = "0.1.0"
authors = ["Stefan Tammer <st.tammer@gmail.com>"]
edition = "2021"

[lib]
name = "winit_platform"
doctest = false


[features]
wake_lock = ["dep:nosleep", "web-sys/Navigator", "web-sys/WakeLock", "web-sys/WakeLockType", "web-sys/WakeLockSentinel"]
iced = ["dep:iced_native", "dep:iced_winit", "web-sys/Navigator", "web-sys/Clipboard", "web-sys/ClipboardEvent", "web-sys/DataTransfer"]
icon_loader = ["dep:icon-loader", "dep:resvg"]


[dependencies]
winit = "0.27"
log = "0"
iced_native = { version = "0.6", optional = true }
iced_winit = { version = "0.5", optional = true }

[target.'cfg(target_os = "linux")'.dependencies]
icon-loader = { version = "0.3", optional = true }
resvg = { version = "0", optional = true }

[target.'cfg(not(target_family = "wasm"))'.dependencies]
pollster = "0.2"
simple_logger = "2"
nosleep = { version = "0.2", optional = true }

[target.'cfg(target_family = "wasm")'.dependencies]
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
web-sys = { version = "0.3" }
js-sys = { version = "0.3" }
console_error_panic_hook = "0.1"
console_log = "0"
