[package]
name = "platform"
version = "0.1.7"
authors = ["Stefan Tammer <st.tammer@gmail.com>"]
edition = "2021"

[lib]
name = "platform"
doctest = false

[workspace]
members = ["run-wasm"]


[features]
wake_lock = ["dep:nosleep", "web-sys/Navigator", "web-sys/WakeLock", "web-sys/WakeLockType", "web-sys/WakeLockSentinel"]
iced = ["dep:wgx", "dep:iced_winit", "dep:iced_wgpu", "web-sys/Navigator", "web-sys/Clipboard", "web-sys/ClipboardEvent", "web-sys/DataTransfer"]
icon_loader = ["dep:icon-loader", "dep:resvg"]


[dependencies]
winit = "0.28"
log = "0"
wgx = { version = "0.16.0", path = "../wgx", optional = true }
iced_winit = { version = "0.10", optional = true }
iced_wgpu = { version = "0.11", optional = true }


[target.'cfg(target_os = "linux")'.dependencies]
icon-loader = { version = "0.3", optional = true }
resvg = { version = "^0.35", optional = true }

[target.'cfg(not(target_family = "wasm"))'.dependencies]
pollster = "0.2"
simple_logger = "2"
nosleep = { version = "0.2", optional = true }

[target.'cfg(target_family = "wasm")'.dependencies]
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
web-sys = { version = "0.3" }
js-sys = { version = "0.3" }
console_error_panic_hook = "0.1"
console_log = "0"


[dev-dependencies]
wgx = { path = "../wgx", features = ["timer", "wgsl_modules", "projection"] }
iced_widget = { version = "*", features = ["canvas"] }
instant = { version = "0.1", features = ["wasm-bindgen"] }


[target.'cfg(target_family = "wasm")'.dev-dependencies]
wgx = { path = "../wgx", features = ["webgl"] }