[package]
name = "winit-platform"
version = "0.1.0"
authors = ["Stefan Tammer <st.tammer@gmail.com>"]
edition = "2021"

[lib]
name = "winit_platform"
doctest = false

[dependencies]
winit = "0.27"
log = "0"

[target.'cfg(not(target_family = "wasm"))'.dependencies]
pollster = "0.2"
simple_logger = "2"

[target.'cfg(target_family = "wasm")'.dependencies]
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
web-sys = { version = "0.3" }
console_error_panic_hook = "0.1"
console_log = "0"