[package]
name = "platform"
version = "0.1.4"
authors = ["Stefan Tammer <st.tammer@gmail.com>"]
edition = "2021"

[lib]
name = "platform"
doctest = false

[workspace]
members = ["run-wasm"]


[features]
wake_lock = ["dep:nosleep", "web-sys/Navigator", "web-sys/WakeLock", "web-sys/WakeLockType", "web-sys/WakeLockSentinel"]
iced = ["dep:wgx", "dep:iced_native", "dep:iced_winit", "dep:iced_wgpu", "web-sys/Navigator", "web-sys/Clipboard", "web-sys/ClipboardEvent", "web-sys/DataTransfer"]
icon_loader = ["dep:icon-loader", "dep:resvg"]


[patch.crates-io]
# patch iced wasm builds
iced_native = { git = "https://github.com/bungoboingo/iced", rev = "365f37a" }
iced_winit = { git = "https://github.com/bungoboingo/iced", rev = "365f37a" }
iced_wgpu = { git = "https://github.com/bungoboingo/iced", rev = "365f37a" }
iced_graphics = { git = "https://github.com/bungoboingo/iced", rev = "365f37a" }


[dependencies]
winit = "0.27"
log = "0"
wgx = { path = "../wgx", optional = true }
iced_native = { version = "0.6", optional = true }
iced_winit = { version = "0.5", optional = true }
iced_wgpu = { version = "0.6", optional = true }

[target.'cfg(target_os = "linux")'.dependencies]
icon-loader = { version = "0.3", optional = true }
resvg = { version = "0.29", optional = true }

[target.'cfg(not(target_family = "wasm"))'.dependencies]
pollster = "0.2"
simple_logger = "2"
nosleep = { version = "0.2", optional = true }

[target.'cfg(target_family = "wasm")'.dependencies]
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
web-sys = { version = "0.3" }
js-sys = { version = "0.3" }
console_error_panic_hook = "0.1"
console_log = "0"


# dev-dependecies
[target.'cfg(not(target_family = "wasm"))'.dev-dependencies]
wgx = { path = "../wgx", features = ["timer"] }
iced_graphics = { version = "*", features = ["canvas"] }

[target.'cfg(target_family = "wasm")'.dev-dependencies]
wgx = { path = "../wgx", features = ["timer", "webgl"] }