[package]
name = "winit-platform"
version = "0.1.0"
authors = ["Stefan Tammer <st.tammer@gmail.com>"]
edition = "2021"

[lib]
name = "winit_platform"
doctest = false

[build]
rustflags = ["--cfg=web_sys_unstable_apis"]


[features]
wake_lock = ["dep:nosleep", "web-sys/Navigator", "web-sys/WakeLock", "web-sys/WakeLockType", "web-sys/WakeLockSentinel"]
iced = ["dep:iced_winit"]

[dependencies]
winit = "0.27"
iced_winit = { git = "https://github.com/iced-rs/iced/", rev = "77c8380", optional = true }
log = "0"

[target.'cfg(not(target_family = "wasm"))'.dependencies]
pollster = "0.2"
simple_logger = "2"
nosleep = { version = "0.2", optional = true }

[target.'cfg(target_family = "wasm")'.dependencies]
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
web-sys = { version = "0.3" }
console_error_panic_hook = "0.1"
console_log = "0"
